version: "3"
services:
  cmc_mysql:
    image: mysql:8
    environment:
     - MYSQL_ALLOW_EMPTY_PASSWORD=true
    restart: unless-stopped
    volumes:
     - ~/.cnp/docker_mysql_data:/var/lib/mysql
    ports:
     - "3306:3306"
  cmc_redis:
    image: redis
    restart: unless-stopped
    ports:
     - "6379:6379"
